"""One-command replication of this report from the frozen captures.

Default (stdlib only, no network): regenerate the figures, verify that every
number the report publishes ties to the sealed data, and confirm the provenance
chain is intact.

    python run_all.py

What is NOT re-run here, by design: the live measurement of the registry. The
captures under ``data/raw/`` and the sealed JSONs under ``output/`` are frozen
evidence of what the network returned on 2026-08-25 (live) and 2025-09-23
(Internet Archive). The instruments that produced them are released and can be
re-run against the live site:

    python code/measure_public_search.py     # exits non-zero once the search filters
    python code/measure_archive_timeline.py   # exits non-zero if the captures diverge

Those exits are the point: this finding is meant to expire the day the registry
repairs its search, and the repair -- not this report -- becomes the outcome of
record. See REPRODUCIBILITY.md for the two-seals contract.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def run(*cmd: str) -> None:
    """Run one replication step from the repository root, failing loudly."""
    print(f"\n=== {' '.join(cmd)}")
    subprocess.run([sys.executable, *cmd], check=True, cwd=ROOT)


def main() -> None:
    """Regenerate, verify, and re-seal-check the published artifact."""
    run("code/make_figure.py", "--lang", "en")
    run("code/make_figure.py", "--lang", "pt")
    run("code/quality_checks.py", "--offline")
    run("-m", "pytest", "tests", "-q")
    run("scripts/verify_chain.py")
    print(
        "\nReplication complete: figures regenerated byte-identically, every published "
        "number tied to the frozen data, provenance verified."
    )


if __name__ == "__main__":
    main()
