"""Seal this replication into a Merkle tree + hash chain.

Two seals, deliberately distinct (see REPRODUCIBILITY.md):

  * EVIDENCE is frozen. The raw captures under ``data/raw/`` and the sealed JSONs
    under ``output/`` are what the network returned on the stated dates. They are
    NOT re-runnable on demand and are not meant to be: the instruments in
    ``code/`` exit non-zero the day the registry repairs its search, which is the
    intended end of this finding. The chain proves the captures were not altered
    since capture -- not that they can be reproduced.
  * DERIVATION is reproducible, and here it is reproducible to the byte. The
    figures are generated by pure-stdlib Python with no plotting library, so
    ``make_figure.py`` emits byte-identical SVGs on any machine. They are
    therefore folded INTO the root, unlike matplotlib figures in sister repos.

Per-stage Merkle roots fold left-to-right into ``artifact_root`` (the chain tip).
Any byte change in any sealed file changes it. The environment fingerprint is
recorded as CONTEXT and is NOT folded in, so the root stays portable.

Usage: python scripts/build_chain.py   ->  PROVENANCE.json
"""

from __future__ import annotations

import datetime as dt
import json
import subprocess
from pathlib import Path

from hash_utils import (
    environment_fingerprint,
    hash_chain,
    merkle_root,
    save_json,
    sha256_file,
    sha256_hex,
)

ROOT = Path(__file__).resolve().parent.parent

CODE_GLOBS = ["code/*.py", "scripts/*.py", "tests/*.py"]
EVIDENCE_GLOBS = ["data/raw/*", "data/raw/wayback/*", "data/derived/*"]
SEALED_RESULTS = [
    "output/public-search-vs-database.json",
    "output/archive-timeline.json",
    "output/downstream-mentions.json",
    "output/repair-2026-09-04/defect1-tls.json",
    "output/repair-2026-09-04/public-search.json",
    "output/repair-2026-09-04/ct-log-ensaiosclinicos.json",
]
FIGURES = ["output/figures/fig1-defect1-chain.svg", "output/figures/fig1-defect1-chain-pt.svg"]
PAPER = [
    "docs/paper/MANUSCRIPT-en.md",
    "docs/paper/MANUSCRITO-pt-BR.md",
    "docs/paper/QUALITY-CALIBRATION.md",
]


def _leaves(rel_paths: list[str]) -> dict[str, str]:
    """Ordered ``{relative_path: sha256}`` for a fixed file list (skips missing)."""
    return {rel: sha256_file(ROOT / rel) for rel in sorted(rel_paths) if (ROOT / rel).exists()}


def _glob_leaves(globs: list[str]) -> dict[str, str]:
    """Ordered ``{relative_path: sha256}`` over globs, caches excluded."""
    rels = sorted(
        {
            str(p.relative_to(ROOT))
            for g in globs
            for p in ROOT.glob(g)
            if p.is_file() and "__pycache__" not in p.parts
        }
    )
    return {rel: sha256_file(ROOT / rel) for rel in rels}


def _git_commit() -> str:
    """Return the current HEAD, or ``UNKNOWN`` outside a git tree."""
    try:
        return (
            subprocess.check_output(
                ["git", "rev-parse", "HEAD"], stderr=subprocess.DEVNULL, cwd=ROOT
            )
            .decode()
            .strip()
        )
    except Exception:
        return "UNKNOWN"


def _stage(name: str, kind: str, leaves: dict[str, str]) -> dict:
    """One sealed stage: its leaves, their Merkle root, and the stage hash."""
    root = merkle_root(list(leaves.values()))
    return {"name": name, "kind": kind, "merkle_root": root, "leaves": leaves, "hash": root}


def compute_provenance() -> dict:
    """Compute the provenance tree and chain from the files on disk.

    Pure: ``build_chain`` writes the result, ``verify_chain`` recomputes and compares.
    """
    env = environment_fingerprint()
    env_hash = sha256_hex(json.dumps(env, sort_keys=True, ensure_ascii=False).encode("utf-8"))
    stages = [
        _stage("code", "derivation-input", _glob_leaves(CODE_GLOBS)),
        _stage("evidence", "frozen-evidence", _glob_leaves(EVIDENCE_GLOBS)),
        _stage("results", "frozen-evidence", _leaves(SEALED_RESULTS)),
        _stage("figures", "reproducible-derivation", _leaves(FIGURES)),
        _stage("paper", "artifact", _leaves(PAPER)),
    ]
    links, artifact_root = hash_chain([s["hash"] for s in stages])
    for s, link in zip(stages, links, strict=False):
        s["chain_link"] = link
    return {
        "provenance_version": "1.0",
        "algorithm": "sha256",
        "paper": (
            "When a trial registry outsources its own search: measured defects "
            "in the public search of ReBEC"
        ),
        "semantics": {
            "evidence": (
                "frozen -- network captures of 2026-08-25 (live endpoints) and of "
                "2025-09-23 (Internet Archive); not re-runnable on demand, and the "
                "instruments exit non-zero once the registry repairs the search"
            ),
            "derivation": (
                "reproducible to the byte -- the figures are pure-stdlib SVG with no "
                "plotting library, so they regenerate identically on any machine"
            ),
            "artifact_root": (
                "portable, machine-independent tamper-evidence over code + raw "
                "captures + sealed results + figures + paper"
            ),
        },
        "sealed_by_interpreter": {
            "python": env.get("python_version"),
            "platform": env.get("platform"),
            "sha256": env_hash,
            "note": "signing interpreter only; NOT folded into artifact_root",
        },
        "stages": stages,
        "chain_order": [s["name"] for s in stages],
        "artifact_root": artifact_root,
        "doi_anchor": "set at release: the Zenodo Version DOI binds this artifact_root",
    }


def main() -> None:
    """Write ``PROVENANCE.json`` and a sealed ``runs/<id>/``."""
    provenance = compute_provenance()
    save_json(provenance, ROOT / "PROVENANCE.json")

    run_id = dt.datetime.now(dt.UTC).strftime("%Y%m%dT%H%M%SZ")
    run_dir = ROOT / "runs" / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    save_json(
        {
            "run_id": run_id,
            "created_utc": dt.datetime.now(dt.UTC).isoformat(),
            "git": {"repository_url": "set at release", "commit": _git_commit(), "tag": None},
            "environment": environment_fingerprint(),
            "artifact_root": provenance["artifact_root"],
            "chain_algorithm": "sha256 Merkle-per-stage + left-fold chain (scripts/build_chain.py)",
            "notes": "rebec-search-fidelity seal; captures frozen, figures byte-reproducible",
        },
        run_dir / "manifest.json",
    )
    save_json(provenance, run_dir / "chain.json")
    sealed = [rel for s in provenance["stages"] for rel in s["leaves"]]
    (run_dir / "checksums.sha256").write_text(
        "\n".join(f"{sha256_file(ROOT / rel)}  {rel}" for rel in sealed) + "\n", encoding="utf-8"
    )

    print(f"[OK] artifact_root = {provenance['artifact_root']}")
    print(f"[OK] {len(sealed)} files sealed across {len(provenance['stages'])} stages")
    print(f"[OK] PROVENANCE.json + runs/{run_id}/ (manifest, chain, checksums)")


if __name__ == "__main__":
    main()
